# Generated by Django 4.2 on 2023-04-26 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_rename_applied_date_eventparticipation_applied_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='criteria',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
