# Generated by Django 4.2 on 2023-04-26 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_criteria_alter_team_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventparticipation',
            name='team',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='events.team'),
        ),
    ]
