# Generated by Django 4.2 on 2023-04-27 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_eventparticipation_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='picture',
            field=models.ImageField(blank=True, default='\\static-images\\events\\event1.jpg', upload_to='events_pics'),
        ),
        migrations.AlterField(
            model_name='eventparticipation',
            name='cover_picture',
            field=models.ImageField(blank=True, default='\\participations_coverpics\\TeamBTC.png', upload_to='participations_coverpics'),
        ),
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, default='\\teams_logos\\TeamBTC.png', upload_to='teams_logos'),
        ),
    ]
