# Generated by Django 4.2 on 2023-04-27 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryitem',
            name='image',
        ),
        migrations.AddField(
            model_name='gallery',
            name='Gallery_slug',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gallery',
            name='second_title',
            field=models.TextField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gallery',
            name='slider_image1',
            field=models.ImageField(blank=True, null=True, upload_to='static-images/gallery/gallery_pics'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='slider_image2',
            field=models.ImageField(blank=True, null=True, upload_to='static-images/gallery/gallery_pics'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='slider_image3',
            field=models.ImageField(blank=True, null=True, upload_to='static-images/gallery/gallery_pics'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='slider_image4',
            field=models.ImageField(blank=True, null=True, upload_to='static-images/gallery/gallery_pics'),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='GalleryImage',
            field=models.ImageField(default='', upload_to='static-images/gallery/event_gallery/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gallery',
            name='cover_image',
            field=models.ImageField(upload_to='static-images/gallery/event_gallery_covers/'),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='static-images/gallery/event_gallery/'),
        ),
    ]
