# Generated by Django 4.2 on 2023-04-27 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_blogpost_subtitle_alter_blogpost_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='author',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='slider_image1',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='slider_image2',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='slider_image3',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='slider_image4',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='slider_image5',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='slug',
        ),
    ]
