# Generated by Django 4.2 on 2023-04-24 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='employment_status',
            field=models.CharField(max_length=20),
        ),
    ]
