# Generated by Django 4.2 on 2023-04-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_employment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='employment_status',
            field=models.CharField(choices=[('Internee', 'Internee'), ('Full-time Job', 'Full-time Job'), ('Part-time Job', 'Part-time Job'), ('Freelancer', 'Freelancer'), ('None', 'None')], max_length=20),
        ),
    ]
