# Generated by Django 4.2 on 2023-04-25 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_domain_clubapplication_domains_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubapplication',
            name='accepted',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
