# Generated by Django 4.2 on 2023-04-26 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_clubmembership_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubmembership',
            name='application',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='accounts.clubapplication'),
        ),
    ]
